### ISSUE TITLE
🎨 [Avanguardie Storiche —> Arte fra le due guerre]

### ISSUE THREAD

**Issue by andreazangheri** [typerror/historiette#2]
#2 Parziale [Avanguardie Storiche —> Arte fra le due guerre]
- [x] Espressionismo #12 
- [x] Cavaliere Azzurro: Der Blaue Reiter #13 
- [x] Cubismo #14 
- [x] Futurismo #15 
- [x] Avanguardie russe: Suprematismo, Costruttivismo #16 
- [x] De Stijl, Neoplasticismo #17 
- [x] Bauhaus #18 
- [x] Dadaismo #19 
- [x] Surrealismo #20 
- [x] Art Déco #21 
- [x] Metafisica #22 
- [x] Espressionismo tedesco #23 
- [x] Novecento #24 
- [x] Cercle et Carré #25 
- [x] Abstraction-Création #26 
- [ ] Astrattismo: Calder, Moore, Hans #27 
- [ ] Muralismo #28 
- [ ] Realismo #29
- [ ] Informale #30
- [ ] Espressionismo Astratto #31
- [ ] Invio email richiesta parziale
