### ISSUE TITLE
🎨 [Arte del dopoguerra —> Video Arte]

### ISSUE THREAD

**Issue by andreazangheri** [typerror/historiette#3]
#3 Parziale [Anni Sessanta—> Video Arte]
- [ ] Arte Cinetica, Optical art #32 
- [ ] New Dada, Pop art, Nouveau Réalisme #33 
- [ ] Klein, Manzoni #34 
- [ ] Minimal art #35 
- [ ] Arte Processuale, Land art #36 
- [ ] Arte Concettuale #37 
- [ ] Arte Povera, Neoavanguardie #38 
- [ ] Happening, Performance, Comportamento #39 
- [ ] Video arte #40 
- [ ] Ritorno alla pittura
- [ ] Arte relazionale
- [ ] Invio email richiesta parziale
